name: Simple Action
on: workflow_dispatch
jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Joe
      - name:
        run: echo "${{ steps.greet.outputs.time }}"