name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Joe'
        required: false


jobs:
  calling-a-reusable-workflow:
    uses: jwilkicki/workflows/.github/workflows/reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
